--
-- PostgreSQL database dump
--

\restrict TpUEmb9D46ncQ7sNi06S2pNFFMx7fPVegdnP7EbJ5PsNGqaLYMZQ3ICDrMLdY06

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg12+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: dynevest_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO dynevest_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO dynevest_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO dynevest_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO dynevest_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO dynevest_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO dynevest_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO dynevest_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_accountcompliance; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_accountcompliance (
    id bigint NOT NULL,
    is_premium_verified boolean NOT NULL,
    verification_progress_percentage integer CONSTRAINT core_accountcompliance_verification_progress_percentag_not_null NOT NULL,
    required_deposit_received boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_accountcompliance OWNER TO dynevest_user;

--
-- Name: core_accountcompliance_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_accountcompliance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_accountcompliance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_deposit; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_deposit (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    proof character varying(100) NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_deposit OWNER TO dynevest_user;

--
-- Name: core_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_integrationsettings; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_integrationsettings (
    id bigint NOT NULL,
    connected_service_name character varying(50) NOT NULL,
    public_identifier character varying(255),
    is_verified boolean NOT NULL,
    last_synced timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_integrationsettings OWNER TO dynevest_user;

--
-- Name: core_integrationsettings_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_integrationsettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_integrationsettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_investment; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_investment (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    plan_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_investment OWNER TO dynevest_user;

--
-- Name: core_investment_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_investment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_investment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_plan; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_plan (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(12,2) NOT NULL,
    duration_days integer NOT NULL,
    roi_percentage numeric(5,2) NOT NULL
);


ALTER TABLE public.core_plan OWNER TO dynevest_user;

--
-- Name: core_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_profile; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_profile (
    id bigint NOT NULL,
    balance numeric(12,2) NOT NULL,
    user_id integer NOT NULL,
    total_profit numeric(12,2) NOT NULL,
    mining_rate numeric(7,4) NOT NULL,
    mining_balance numeric(12,2) NOT NULL,
    require_external_deposit boolean NOT NULL,
    required_deposit_percentage integer NOT NULL,
    withdrawal_locked boolean NOT NULL
);


ALTER TABLE public.core_profile OWNER TO dynevest_user;

--
-- Name: core_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_transaction; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_transaction (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    fee numeric(12,2) NOT NULL,
    wallet_address character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    transaction_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_transaction OWNER TO dynevest_user;

--
-- Name: core_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_withdrawal; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.core_withdrawal (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    wallet_address character varying(255) NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_withdrawal OWNER TO dynevest_user;

--
-- Name: core_withdrawal_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.core_withdrawal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_withdrawal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO dynevest_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO dynevest_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO dynevest_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: dynevest_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: dynevest_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO dynevest_user;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add profile	10	add_profile
26	Can change profile	10	change_profile
27	Can delete profile	10	delete_profile
28	Can view profile	10	view_profile
29	Can add plan	9	add_plan
30	Can change plan	9	change_plan
31	Can delete plan	9	delete_plan
32	Can view plan	9	view_plan
33	Can add deposit	7	add_deposit
34	Can change deposit	7	change_deposit
35	Can delete deposit	7	delete_deposit
36	Can view deposit	7	view_deposit
37	Can add investment	8	add_investment
38	Can change investment	8	change_investment
39	Can delete investment	8	delete_investment
40	Can view investment	8	view_investment
41	Can add withdrawal	11	add_withdrawal
42	Can change withdrawal	11	change_withdrawal
43	Can delete withdrawal	11	delete_withdrawal
44	Can view withdrawal	11	view_withdrawal
45	Can add transaction	12	add_transaction
46	Can change transaction	12	change_transaction
47	Can delete transaction	12	delete_transaction
48	Can view transaction	12	view_transaction
49	Can add integration settings	13	add_integrationsettings
50	Can change integration settings	13	change_integrationsettings
51	Can delete integration settings	13	delete_integrationsettings
52	Can view integration settings	13	view_integrationsettings
53	Can add account compliance	14	add_accountcompliance
54	Can change account compliance	14	change_accountcompliance
55	Can delete account compliance	14	delete_accountcompliance
56	Can view account compliance	14	view_accountcompliance
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$OzOdEEyodvYkJOGqcpqFb9$2ltjAGoiIYmrEN+c3WyWSln0P4xbg9D1PWxbhpO0nfc=	2026-06-01 13:06:11.349056+00	t	batman			batman_wayne@yahoo.com	t	t	2026-05-19 13:56:02+00
11	pbkdf2_sha256$1200000$e94PiEHn001BjtSHJe63OY$P7IB8g6tkJ/lRpqQedjyTygCxp+4PTAgZio85VsHuMI=	2026-06-04 14:51:25.99479+00	f	DerErr0r			c.glossner@proton.me	f	t	2026-06-04 14:51:06.82002+00
10	pbkdf2_sha256$1200000$z5hcmpq7LdHwm1gbze22Q0$U2Brv1FDnV2BGkTkTXYHiaym9gKWwEfqcJNV0wF/fns=	2026-06-03 08:14:48.756988+00	f	Schmidi			jackyschmid@gmail.com	f	t	2026-06-03 08:14:29.621454+00
5	pbkdf2_sha256$1200000$NwOi5vBpHWhCpUaYhatVm2$kgxqdcHc+/zj8fN2cvi5sVLAjkfoIyX5hG/sY9NUlrc=	2026-06-05 10:51:39.805496+00	t	@Haaland			benjaminemmanuel842021@gmail.com	t	t	2026-05-19 16:10:25+00
9	pbkdf2_sha256$1200000$fyVFRYHiVEeMlZWoktFOHO$BC/0v1jfz+y4E0wI27juNX9KLArReHPrFdF514tmYGk=	2026-06-01 12:20:45.083167+00	f	@wagener			sabrinawagener496@gmail.com	f	t	2026-06-01 12:20:25.346716+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_accountcompliance; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_accountcompliance (id, is_premium_verified, verification_progress_percentage, required_deposit_received, user_id) FROM stdin;
\.


--
-- Data for Name: core_deposit; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_deposit (id, amount, proof, status, created_at, user_id) FROM stdin;
1	200000.00	deposit_proofs/payment.jpg	Approved	2026-05-19 14:20:13.15042+00	1
2	200.00	deposit_proofs/IMG_3215.jpeg	Approved	2026-05-19 16:26:55.489585+00	5
3	200.00	deposit_proofs/test_1.jpg	Approved	2026-05-19 16:37:06.277917+00	5
4	1000000.00	deposit_proofs/test_2.png	Approved	2026-05-19 16:51:47.755496+00	1
5	200.00	deposit_proofs/IMG_3429.jpeg	Approved	2026-05-20 21:05:52.285275+00	5
6	200.00	deposit_proofs/IMG_3428.jpeg	Approved	2026-05-20 21:17:02.772209+00	5
7	65567.00	deposit_proofs/IMG_3458.png	Approved	2026-05-22 20:39:38.912724+00	5
9	200.00	deposit_proofs/58764.jpg	Approved	2026-06-03 10:12:31.307374+00	10
10	200.00	deposit_proofs/1000242773.jpg	Approved	2026-06-04 14:53:20.194334+00	11
\.


--
-- Data for Name: core_integrationsettings; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_integrationsettings (id, connected_service_name, public_identifier, is_verified, last_synced, user_id) FROM stdin;
2	Coinbase API	None	f	2026-05-22 21:18:20.308327+00	1
9	Coinbase API	\N	f	2026-06-01 12:20:27.889542+00	9
11	Coinbase API	None	f	2026-06-04 16:07:42.887958+00	11
10	Coinbase API	None	f	2026-06-05 10:41:21.262266+00	10
1	Coinbase API	@Haaland	f	2026-06-05 10:51:16.210033+00	5
\.


--
-- Data for Name: core_investment; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_investment (id, amount, is_active, created_at, plan_id, user_id) FROM stdin;
1	200.00	t	2026-05-19 14:28:59.342385+00	1	1
3	10000.00	t	2026-05-20 09:18:35.739212+00	3	1
6	10000.00	t	2026-05-30 16:13:50.139512+00	3	1
7	5000.00	t	2026-06-01 13:18:30.033179+00	2	1
9	200.00	t	2026-06-05 10:51:46.472078+00	1	5
\.


--
-- Data for Name: core_plan; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_plan (id, name, price, duration_days, roi_percentage) FROM stdin;
1	Silver Plan	200.00	7	10.00
2	Gold plan	5000.00	7	10.00
3	Elite plan	10000.00	7	10.00
\.


--
-- Data for Name: core_profile; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_profile (id, balance, user_id, total_profit, mining_rate, mining_balance, require_external_deposit, required_deposit_percentage, withdrawal_locked) FROM stdin;
10	4218.00	10	0.00	0.3000	0.00	f	10	t
1	2368800.00	1	2139.22	0.0100	2419.53	f	10	f
11	200.00	11	0.00	0.0100	0.00	f	10	f
9	0.00	9	0.00	0.0100	0.00	f	10	f
5	3057.00	5	0.01	15.0000	0.01	f	20	f
\.


--
-- Data for Name: core_transaction; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_transaction (id, amount, fee, wallet_address, status, transaction_type, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: core_withdrawal; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.core_withdrawal (id, amount, wallet_address, status, created_at, user_id) FROM stdin;
1	5000.00	bc1qxy2kgdy	Completed	2026-05-19 15:25:04.950184+00	1
4	1000.00	bc1qxy2kgdy	Completed	2026-05-20 18:28:32.67957+00	1
6	4000.00	Hahhajaksj	Completed	2026-05-21 16:11:24.001445+00	5
7	200.00	dddd	Completed	2026-05-22 11:06:42.340073+00	1
5	10.00	Hhhhhhh	Declined	2026-05-20 22:02:03.235828+00	1
8	100.00	ddddddd	Approved	2026-05-22 13:11:05.748764+00	1
10	400000.00	Jajjajajn	Approved	2026-05-22 22:02:17.373827+00	5
9	50000.00	Hqhhahjaja	Approved	2026-05-22 22:01:53.103501+00	5
12	5900.00	Qtfagajna	Approved	2026-05-23 12:53:28.538993+00	5
11	500.00	Yahjwnwnn	Approved	2026-05-23 12:52:37.084717+00	5
13	2000.00	bc1qxy2kgdy	Approved	2026-05-30 16:12:57.714497+00	5
14	200.00	bc1qxy2kgdy	Approved	2026-06-01 13:19:18.027142+00	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-19 14:27:15.688291+00	1	Silver Plan	1	[{"added": {}}]	9	1
2	2026-05-19 14:27:30.40496+00	2	Gold plan	1	[{"added": {}}]	9	1
3	2026-05-19 14:28:08.12033+00	3	Elite plan	1	[{"added": {}}]	9	1
4	2026-05-19 16:18:45.90061+00	1	batman - $5000.00	2	[{"changed": {"fields": ["Status"]}}]	11	1
5	2026-05-19 16:26:55.490604+00	2	@Haaland - $200 (Approved)	1	[{"added": {}}]	7	1
6	2026-05-19 17:02:39.1577+00	3	@Haaland - $200	1	[{"added": {}}]	11	1
7	2026-05-20 18:29:21.865236+00	4	batman - $1000.00	2	[{"changed": {"fields": ["Status"]}}]	11	1
8	2026-05-20 21:01:57.875211+00	3	@Haaland - $200.00	3		11	1
9	2026-05-20 21:02:30.566968+00	2	@Haaland - $200.00	3		11	1
10	2026-05-20 21:05:52.287472+00	5	@Haaland - $200 (Approved)	1	[{"added": {}}]	7	1
11	2026-05-20 21:10:59.562285+00	5	@Haaland - $200.00 (Approved)	2	[]	7	1
12	2026-05-20 21:18:57.119372+00	6	@Haaland - $200.00 (Approved)	2	[{"changed": {"fields": ["Status"]}}]	7	1
13	2026-05-21 17:15:20.870626+00	6	@Haaland - $4000.00	2	[{"changed": {"fields": ["Status"]}}]	11	1
14	2026-05-22 11:10:50.179439+00	7	batman - $200.00	2	[{"changed": {"fields": ["Status"]}}]	11	1
15	2026-05-22 11:11:45.411145+00	5	batman - $10.00	2	[{"changed": {"fields": ["Status"]}}]	11	1
16	2026-05-30 12:58:55.67168+00	4	selina_kyle	3		4	1
17	2026-05-30 12:59:10.455249+00	2	tony_stark	3		4	1
18	2026-05-30 12:59:26.626695+00	3	clark_k	3		4	1
19	2026-05-30 12:59:44.452447+00	6	DerError	3		4	1
20	2026-05-30 12:59:58.443602+00	7	DerErr0r	3		4	1
21	2026-05-30 14:06:22.945438+00	2	@Haaland - Silver Plan	3		8	1
22	2026-05-30 15:44:14.327999+00	5	@Haaland	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	4	1
23	2026-06-01 08:34:00.722515+00	1	batman	2	[{"changed": {"fields": ["Email address"]}}]	4	1
24	2026-06-01 12:22:37.676126+00	8	@Sabrina	3		4	1
25	2026-06-03 13:35:56.130978+00	5	@Haaland's Profile	2	[{"changed": {"fields": ["Require external deposit"]}}]	10	1
26	2026-06-03 20:03:28.641498+00	9	Schmidi - $200.00 (Approved)	2	[]	7	5
27	2026-06-05 10:47:26.009786+00	4	@Haaland - Silver Plan	3		8	5
28	2026-06-05 10:48:40.599624+00	8	Schmidi - Silver Plan	3		8	5
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	deposit
8	core	investment
9	core	plan
10	core	profile
11	core	withdrawal
12	core	transaction
13	core	integrationsettings
14	core	accountcompliance
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-19 13:05:38.032992+00
2	auth	0001_initial	2026-05-19 13:05:38.231746+00
3	admin	0001_initial	2026-05-19 13:05:38.245184+00
4	admin	0002_logentry_remove_auto_add	2026-05-19 13:05:38.251078+00
5	admin	0003_logentry_add_action_flag_choices	2026-05-19 13:05:38.257981+00
6	contenttypes	0002_remove_content_type_name	2026-05-19 13:05:38.271823+00
7	auth	0002_alter_permission_name_max_length	2026-05-19 13:05:38.322036+00
8	auth	0003_alter_user_email_max_length	2026-05-19 13:05:38.330165+00
9	auth	0004_alter_user_username_opts	2026-05-19 13:05:38.337026+00
10	auth	0005_alter_user_last_login_null	2026-05-19 13:05:38.34545+00
11	auth	0006_require_contenttypes_0002	2026-05-19 13:05:38.347494+00
12	auth	0007_alter_validators_add_error_messages	2026-05-19 13:05:38.355391+00
13	auth	0008_alter_user_username_max_length	2026-05-19 13:05:38.364601+00
14	auth	0009_alter_user_last_name_max_length	2026-05-19 13:05:38.372649+00
15	auth	0010_alter_group_name_max_length	2026-05-19 13:05:38.380726+00
16	auth	0011_update_proxy_permissions	2026-05-19 13:05:38.387617+00
17	auth	0012_alter_user_first_name_max_length	2026-05-19 13:05:38.395653+00
18	core	0001_initial	2026-05-19 13:05:38.424602+00
19	core	0002_plan	2026-05-19 13:05:38.428663+00
20	core	0003_deposit	2026-05-19 13:05:38.447866+00
21	core	0004_investment	2026-05-19 13:05:38.52598+00
22	core	0005_withdrawal	2026-05-19 13:05:38.540297+00
23	core	0006_profile_total_profit	2026-05-19 13:05:38.549538+00
24	core	0007_profile_mining_rate_alter_deposit_amount_and_more	2026-05-19 13:05:38.596622+00
25	sessions	0001_initial	2026-05-19 13:05:38.624416+00
26	core	0008_transaction	2026-05-20 18:26:42.399624+00
27	core	0009_profile_mining_balance	2026-05-20 19:14:36.997576+00
28	core	0010_profile_require_external_deposit_and_more	2026-05-22 12:44:05.425771+00
29	core	0011_integrationsettings	2026-05-22 17:45:01.51322+00
30	core	0012_profile_withdrawal_locked_accountcompliance	2026-05-23 12:44:13.222573+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: dynevest_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
urvzzcuvqye8tn04lw27nz3mzwmkb987	.eJxVjEEOwiAQRe_C2hCYAUpduvcMZIBBqoYmpV0Z765NutDtf-_9lwi0rTVsnZcwZXEWVpx-t0jpwW0H-U7tNss0t3WZotwVedAur3Pm5-Vw_w4q9fqtIQ0jew2gPTqXIaK1xMYq8gbLACqTQkKISifrHKKGwiPprDgVo0fx_gC4Qzb3:1wPosp:q21pqklMTpvDVOfkOA_9_mZnCXcMIUnHwRGwJRj_MMg	2026-06-03 21:55:19.96234+00
xv772tl1fo9met01cjyffu1o73s0k5rt	.eJxVjMEOwiAQRP-FsyGlrcB69O43kF12kaqhSWlPxn-XJj3oaTLzZuatAm5rDluVJUysLsqo029GGJ9SdsAPLPdZx7msy0R6r-iDVn2bWV7Xo_t3kLHmtu5HzzY5Qz0iYMfCoyNODCQdDvbcBNg3h5QMIQB5coO1HDGCE1CfLxkkOZA:1wU2LL:tvFveTOQbWDV3kNTbfmyvZbqOGBNhR-dJUFbGo3TYpc	2026-06-15 13:06:11.351999+00
0zcaz6n2voquq7miilvu4j4yug5oto81	.eJxVjMsOwiAQRf-FtSEwhQzj0r3fQIaXVA0kpV0Z_12bdKHbe865L-F5W6vfRl78nMRZaCVOv2Pg-MhtJ-nO7dZl7G1d5iB3RR50yGtP-Xk53L-DyqN-a7CmADoVGKwOqAkjKxMdck5UcALUgEY5Usg2UMTJcSbrYCKXMhfx_gDhhTdY:1wUgkQ:jzTFJcMBBqQnq_SsTAsUExHfcs6WkDoIYkkJl8oJ_GM	2026-06-17 08:14:46.262929+00
rrkyw8v2xjo28eif9llzreg16nrctn76	.eJxVjMsOwiAQRf-FtSFAebp07zeQGRikaiAp7cr479qkC93ec859sQjbWuM2aIlzZmcm2el3Q0gPajvId2i3zlNv6zIj3xV-0MGvPdPzcrh_BxVG_dYBhdPWUkIdphKkysagDYVIGgvkEIpXKDKq4JKHLIgcCbJT0oWE9Oz9AfOsOJ8:1wR9Mz:KxMV2ht6dAM_9BtU7YP7mRst9heDiKB-5PYP9y5L8Ug	2026-06-07 13:59:57.841658+00
wqeet6cik8kehnro17cn3rz7o6dspf24	.eJxVjMsOwiAQRf-FtSEwhQzj0r3fQIaXVA0kpV0Z_12bdKHbe865L-F5W6vfRl78nMRZaCVOv2Pg-MhtJ-nO7dZl7G1d5iB3RR50yGtP-Xk53L-DyqN-a7CmADoVGKwOqAkjKxMdck5UcALUgEY5Usg2UMTJcSbrYCKXMhfx_gDhhTdY:1wUgkS:K_zMKe2xq_uEGYkaA0FbmxXOgUtZpmNTFOcUuOZb4hE	2026-06-17 08:14:48.759563+00
lanzq5r0ml3f5qo1kcs9hntkime93nml	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6U2:Vd34N37x_uM2UwgfOS8n10MzQh4Vwnj2A0e0P15Vs6I	2026-06-04 16:42:54.499248+00
d6fwrehjawdr7kir8saikrc5tq8el2g7	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6UB:kJ4uIC8mS1abQkqzXt2imqcfdWLHkzDiytlXqH3wMzg	2026-06-04 16:43:03.399972+00
23yy4ve8uk7iixvcnx7qpc45ac6o3os6	.eJxVjEEOgjAQRe_StWnsFIbi0j1nINOZwaKmTSisjHdXEha6_e-9_zIjbWsat6rLOIu5GOfM6XeMxA_NO5E75VuxXPK6zNHuij1otUMRfV4P9-8gUU3fOqD22DGqa6eAUwieAmPbNY4mVQHwXh3EBlgYvSBDI8pKAh2cfd-a9wcJEDhC:1wV9Pp:KYw4POVvP8E_yzDI1jh2XjjYrN6lgMBz8OcHAb8Z7-w	2026-06-18 14:51:25.999067+00
gru0ivmyogvt59jp6af7rc4de3lfwz4r	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6UG:Um8clY5fMvvqppHc6Wu_m6BlHUGf9MqhqM3JFvCWlLk	2026-06-04 16:43:08.212755+00
0lbf8jffmgqff1lnylsbwsq1u9lp5ss9	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6Ua:CgY4CWXiKiB-MXy62Skxd4pHeg5_S0JlWxkiFTssZLM	2026-06-04 16:43:28.098935+00
k88kauyyyvask3vdol5cd3j6kvhj4133	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6Ur:3QScfZ8Zy0_OZiDhdsz_Vmu84pHD8gpMVOFK-mx9fo8	2026-06-04 16:43:45.806363+00
3qrywyfahvegxr4wlvdzxub5hvssw1fj	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6Uu:S57y3MvpXVnUnugjTRVXhnl90zvNgG3rK4FVy9DmLBs	2026-06-04 16:43:48.492396+00
q6r67ls15hi5fzxcge3maz9mhbfvs0id	.eJxVjEEOwiAQRe_C2hCYAUpduvcMZIBBqoYmpV0Z765NutDtf-_9lwi0rTVsnZcwZXEWVpx-t0jpwW0H-U7tNss0t3WZotwVedAur3Pm5-Vw_w4q9fqtIQ0jew2gPTqXIaK1xMYq8gbLACqTQkKISifrHKKGwiPprDgVo0fx_gC4Qzb3:1wVS9L:XMVVSXtlQ6CFFPYCvxuQ5c5-B2p0Nsz8gytHbJYBuxI	2026-06-19 10:51:39.809105+00
9hohh57ja6tjvuvqc9h6qn5i2rlz3btu	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6V1:CqhQKBJUVT0RQtG-V4HqRGGnyF7HD0aM9q-D5xV7Si4	2026-06-04 16:43:55.69559+00
iha7ohxr640745acqc2z5tx3p6pt8d8i	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6V4:esIPNIicMmqGxaQ9YshAP2sin4tnmYCU5r38YQsJrRk	2026-06-04 16:43:58.198438+00
qc05de2itm5k854a34o2xboavs3e7oy1	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6VT:uC5yEVAHbTQHZk1OeTnCIjzxydtpf53xqunYkxhcLoM	2026-06-04 16:44:23.402163+00
yiqwotjt7gl99iooq6yp78q8ib3853ow	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6Ve:rxzD6Qin1pVr3B4Bg-VT-Jyo62aCtma1JMSYnCb5Nts	2026-06-04 16:44:34.397653+00
t310z0e0c3q8aycl2tnygxhlhdlgqgcb	.eJxVjL0OwyAQg9-FuULhCH8du-cZ0AFHSVsRKSRT1XcvkTK03uzP9pt53Lfi90arnxO7MsEuv1nA-KR6gPTAel94XOq2zoEfFX7Sxqcl0et2dv8OCrbS16PpCkAKAbUlLaxRQCK4mLNJOZOWYhDWoQTd_aAljDGglVaCyg7Y5wvVoTdX:1wQ6Vh:Xq5NQnVkypCbUvb5EfOLe548G-GH1Tvn4gxMCNMTcSw	2026-06-04 16:44:37.099924+00
vyd884yuyl2tuyy2vrsvy2h98die4946	.eJxVjMsOwiAQRf-FtSGUwsC4dO83kCkzSNXQpI-V8d-1SRe6veec-1KJtrWmbZE5jazOqlOn322g_JC2A75Tu006T22dx0Hvij7ooq8Ty_NyuH8HlZb6rQlzQUYANKZQ54IM1rGEKB6i8z1GLoaMZ29BkKzvKQNQiCYCEgT1_gDgqjdn:1wPiPM:QH_wUnzS7OyiNVpNlk_hIzIhs1ZgFngM1sZk7Bdei4w	2026-06-03 15:00:28.827546+00
9rcp2srorg869s3citqlrupx6y2yj7pg	.eJxVjMsOwiAQRf-FtSGUwsC4dO83kCkzSNXQpI-V8d-1SRe6veec-1KJtrWmbZE5jazOqlOn322g_JC2A75Tu006T22dx0Hvij7ooq8Ty_NyuH8HlZb6rQlzQUYANKZQ54IM1rGEKB6i8z1GLoaMZ29BkKzvKQNQiCYCEgT1_gDgqjdn:1wPiPP:ffsTY_d5D8Ay4-hAadBlrbxHncMER76q6K3ChWlfcFA	2026-06-03 15:00:31.838156+00
l0setxtzs3esfsg7os4dja27calmbj2s	.eJxVjMsOgjAUBf-la9NA6YPr0j3f0NyXFjWQUFgZ_11JWOj2zMx5mYzbWvJWdcmjmLNpzel3I-SHTjuQO0632fI8rctIdlfsQasdZtHn5XD_DgrW8q0bIIkkXiWy9Nxzh9TylXxCCcBdcAAuiFPoI4P3ShK6mBqU1KqAN-8PESg4pw:1wQ8B0:RtdC_qSzdaGzUFnAC4DZxTO6d0wZXLyFoUFP7uNXOVs	2026-06-04 18:31:22.890295+00
iyp5ebgkr11dvayydjq3hzn5qtfu7nme	.eJxVjMsOgjAUBf-la9NA6YPr0j3f0NyXFjWQUFgZ_11JWOj2zMx5mYzbWvJWdcmjmLNpzel3I-SHTjuQO0632fI8rctIdlfsQasdZtHn5XD_DgrW8q0bIIkkXiWy9Nxzh9TylXxCCcBdcAAuiFPoI4P3ShK6mBqU1KqAN-8PESg4pw:1wQ8B3:zsT2i9tUfePrbShJz9dWuRqWUt9pXZvvVuElaVKz_54	2026-06-04 18:31:25.3896+00
p6vjuwb8swo2iryeil6a9l42crw4bf4x	.eJxVjMEOwiAQRP-FsyGlrcB69O43kF12kaqhSWlPxn-XJj3oaTLzZuatAm5rDluVJUysLsqo029GGJ9SdsAPLPdZx7msy0R6r-iDVn2bWV7Xo_t3kLHmtu5HzzY5Qz0iYMfCoyNODCQdDvbcBNg3h5QMIQB5coO1HDGCE1CfLxkkOZA:1wTMJN:KpazPHrJ6m44apHf4mjaWQfnOB7qzpc1vnScham5Iis	2026-06-13 16:13:21.020523+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 11, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_accountcompliance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_accountcompliance_id_seq', 1, false);


--
-- Name: core_deposit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_deposit_id_seq', 10, true);


--
-- Name: core_integrationsettings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_integrationsettings_id_seq', 11, true);


--
-- Name: core_investment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_investment_id_seq', 9, true);


--
-- Name: core_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_plan_id_seq', 3, true);


--
-- Name: core_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_profile_id_seq', 11, true);


--
-- Name: core_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_transaction_id_seq', 1, false);


--
-- Name: core_withdrawal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.core_withdrawal_id_seq', 14, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 28, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dynevest_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_accountcompliance core_accountcompliance_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_accountcompliance
    ADD CONSTRAINT core_accountcompliance_pkey PRIMARY KEY (id);


--
-- Name: core_accountcompliance core_accountcompliance_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_accountcompliance
    ADD CONSTRAINT core_accountcompliance_user_id_key UNIQUE (user_id);


--
-- Name: core_deposit core_deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_deposit
    ADD CONSTRAINT core_deposit_pkey PRIMARY KEY (id);


--
-- Name: core_integrationsettings core_integrationsettings_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_integrationsettings
    ADD CONSTRAINT core_integrationsettings_pkey PRIMARY KEY (id);


--
-- Name: core_integrationsettings core_integrationsettings_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_integrationsettings
    ADD CONSTRAINT core_integrationsettings_user_id_key UNIQUE (user_id);


--
-- Name: core_investment core_investment_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_investment
    ADD CONSTRAINT core_investment_pkey PRIMARY KEY (id);


--
-- Name: core_plan core_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_plan
    ADD CONSTRAINT core_plan_pkey PRIMARY KEY (id);


--
-- Name: core_profile core_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_profile
    ADD CONSTRAINT core_profile_pkey PRIMARY KEY (id);


--
-- Name: core_profile core_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_profile
    ADD CONSTRAINT core_profile_user_id_key UNIQUE (user_id);


--
-- Name: core_transaction core_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_transaction
    ADD CONSTRAINT core_transaction_pkey PRIMARY KEY (id);


--
-- Name: core_withdrawal core_withdrawal_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_withdrawal
    ADD CONSTRAINT core_withdrawal_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_deposit_user_id_08d2a8f8; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX core_deposit_user_id_08d2a8f8 ON public.core_deposit USING btree (user_id);


--
-- Name: core_investment_plan_id_f3501fa5; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX core_investment_plan_id_f3501fa5 ON public.core_investment USING btree (plan_id);


--
-- Name: core_investment_user_id_767a6d02; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX core_investment_user_id_767a6d02 ON public.core_investment USING btree (user_id);


--
-- Name: core_transaction_user_id_9d7207a3; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX core_transaction_user_id_9d7207a3 ON public.core_transaction USING btree (user_id);


--
-- Name: core_withdrawal_user_id_95a18d1e; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX core_withdrawal_user_id_95a18d1e ON public.core_withdrawal USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: dynevest_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_accountcompliance core_accountcompliance_user_id_35b41c1f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_accountcompliance
    ADD CONSTRAINT core_accountcompliance_user_id_35b41c1f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_deposit core_deposit_user_id_08d2a8f8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_deposit
    ADD CONSTRAINT core_deposit_user_id_08d2a8f8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_integrationsettings core_integrationsettings_user_id_bec7abc1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_integrationsettings
    ADD CONSTRAINT core_integrationsettings_user_id_bec7abc1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_investment core_investment_plan_id_f3501fa5_fk_core_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_investment
    ADD CONSTRAINT core_investment_plan_id_f3501fa5_fk_core_plan_id FOREIGN KEY (plan_id) REFERENCES public.core_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_investment core_investment_user_id_767a6d02_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_investment
    ADD CONSTRAINT core_investment_user_id_767a6d02_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_profile core_profile_user_id_bf8ada58_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_profile
    ADD CONSTRAINT core_profile_user_id_bf8ada58_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_transaction core_transaction_user_id_9d7207a3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_transaction
    ADD CONSTRAINT core_transaction_user_id_9d7207a3_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_withdrawal core_withdrawal_user_id_95a18d1e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.core_withdrawal
    ADD CONSTRAINT core_withdrawal_user_id_95a18d1e_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dynevest_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO dynevest_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO dynevest_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO dynevest_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO dynevest_user;


--
-- PostgreSQL database dump complete
--

\unrestrict TpUEmb9D46ncQ7sNi06S2pNFFMx7fPVegdnP7EbJ5PsNGqaLYMZQ3ICDrMLdY06

