# Generated by Django 6.0.5 on 2026-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
