# Generated by Django 6.0.5 on 2026-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_mining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='require_external_deposit',
            field=models.BooleanField(default=False, help_text='Toggle if this user must deposit before withdrawing'),
        ),
        migrations.AddField(
            model_name='profile',
            name='required_deposit_percentage',
            field=models.IntegerField(default=10, help_text='Percentage (10-30%) required based on withdrawal amount'),
        ),
    ]
