# Generated by Django 6.0.5 on 2026-05-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_require_external_deposit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_service_name', models.CharField(default='Coinbase API', max_length=50)),
                ('public_identifier', models.CharField(blank=True, help_text='The public API key or username used for read-only data synchronization.', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
