# Generated by Django 6.0.5 on 2026-05-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_integrationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawal_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium_verified', models.BooleanField(default=False)),
                ('verification_progress_percentage', models.IntegerField(default=0)),
                ('required_deposit_received', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
